### ISSUE TITLE
Authentication failed: The specified member name is either invalid or empty.

### ISSUE THREAD

**Issue by marcfath** [vgrem/phpSPO#13]
Regardless of what I put in the userid and password parameters (valid or not) I get the same return from acquireTokenForUser call.  I have tried valid userids (which I can log in to Sharepoint with) and dummy userids I expect to fail....same result.

**Comment by robertblock** [comment]
I'm having the same issue, though I don't know a lot about Sharepoint. Yet.

**Comment by ctcudd** [comment]
What kind of Sharepoint instance are you connecting to?

If you are connecting to a local Sharepoint instance, aka "Sharepoint Intranet", please try the [NtlmConnectExample](https://github.com/vgrem/phpSPO/blob/master/examples/NtlmConnectExample.php)

**Comment by vgrem** [comment]
I propose to close this issue since could not reproduce this issue

To summarize, in case of SharePoint authentication:

1. [NetworkCredentialContext class](https://github.com/vgrem/phpSPO/blob/master/src/Runtime/Auth/NetworkCredentialContext.php) - support basic, digest, NTLM, and Kerberos authentication schemes(SharePoint On-Premise)

2. [AuthenticationContext class](https://github.com/vgrem/phpSPO/blob/master/src/Runtime/Auth/AuthenticationContext.php) / used for SharePoint Online & Office 365 authentication

**Comment by mpastas** [comment]
I'm getting exactly the same message trying to connect to Sharepoint Online:

**The specified member name is either invalid or empty.**
    ```
    $username = "john.doe"; //Not using the @domain.com
    $password = "password"
    $authCtx = new AuthenticationContext($url);
    $authCtx->acquireTokenForUser($username, $password);
    $ctx = new ClientContext($url, $authCtx);
```

**Comment by Sofiaaccount** [comment]
Same issue here, with correct login pass i get  Authentication failed: Warning: DOMXPath::query(): Undefined namespace prefix

how can i resolve this ?
Thanks

**Comment by Eiglimar** [comment]
hello guys anyone solved this?
