### ISSUE TITLE
Support for SharePoint Search REST API

### ISSUE THREAD

**Issue by filippotoso** [vgrem/phpSPO#135]
Hi,

does phpSPO support SharePoint Search REST API?

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview

In alternative, is there any way to execute a "raw" query?

I tried different codes with executeQueryDirect() but I always get _"HTTP Error 400. The request is badly formed."_

Thanks,
Filippo Toso

**Comment by vgrem** [comment]
Greetings!

SharePoint Search namespace is not  supported but indeed it could be perfoemed via `executeQueryDirect` method as "raw" query.

Here is a sample GET request from [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview)

`http:// server/_api/search/query?querytext='sharepoint'&enableinterleaving=true ` 

It could be converted to the following  example

```
$request = new RequestOptions($siteUrl . "/_api/search/query?querytext='guide'");
$response = $ctx->executeQueryDirect($request);
```

Since by default the response payload is returned in JSON format,  `$response` could be parsed like this:

```
$jsonResponse = json_decode($response); #convert to JSON object first
#extract search results from JSON payload (of Microsoft.Office.Server.Search.REST.SearchResult type)
$searchResult = $jsonResponse->d->query;
$rows = $searchResult->PrimaryQueryResult->RelevantResults->Table->Rows->results;
foreach($rows as $row) {
    $path = $row->Cells->results[6]->Value;  #get Path property
    echo $path . "\n";
}
```




**Complete example**

$authCtx = new AuthenticationContext($siteUrl);
$authCtx->acquireTokenForUser($userCreds['UserName'],$userCreds['Password']); //authenticate via user creds
$ctx = new ClientContext($siteUrl,$authCtx);

$request = new RequestOptions($siteUrl . "/_api/search/query?querytext='guide'");
$response = $ctx->executeQueryDirect($request);
$jsonResponse = json_decode($response);

$searchResult = $jsonResponse->d->query;
$rows = $searchResult->PrimaryQueryResult->RelevantResults->Table->Rows->results;
foreach($rows as $row) {
    $path = $row->Cells->results[6]->Value;
    echo $path . "\n";
}

**Comment by bgosaric** [comment]
Hi @vgrem, 
first thank you for this guidance through the QueryDirect possibility. 
I´m not able to deal with the $jsonResponse since it considers as response an object, like object(Office365\Runtime\Http\Response)#19 (2) { ["StatusCode":protected]=> int(200) ["Content":protected]=> string(10802) "{"d":{"query":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchResult"},"ElapsedTime":0,"PrimaryQueryResult":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.QueryResult"},"CustomResults":{"__metadata":{"type":"Collection(Microsoft.Office.Server.Search.REST.CustomResult)"},"results": .......

when i dump the $response i can see everything from the object including the: ... {"__metadata":{"type":"SP.KeyValue"},"Key":"HitHighlightedSummary","Value":"V000334 ... that is what i´m looking for. 

But following your example it´s failing on the $searchResult -> Undefined property: stdClass::$d. 
Could you please direct me to solve the issue and also point to any documentation i could read to go deeper in similar cases?
thank you in advance,
B.

**Comment by bgosaric** [comment]
Hi vgrem,
thank you for the detaile explanation related to this approach. 

The loop through the response is not working in the way you presented since "By default, results are returned in XML format.". Is there a way to pass headers within the request?

the response is something like: object(Office365\Runtime\Http\Response)#20 (2) { ["StatusCode":protected]=> int(200) ["Content":protected]=> string(654689) "{"d":{"query":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.SearchResult"},"ElapsedTime":0,"PrimaryQueryResult":{"__metadata":{"type":"Microsoft.Office.Server.Search.REST.QueryResult"},"CustomResults":{"__metadata":{"type":"Collection(Microsoft.Office.Server.Search.REST.CustomResult)"},"results":[]},"QueryId":"b952fd12-bd0e-4505-8d48-9bc29e312679","QueryRuleId":"00000000-0000-0000-0000-000000000000","RefinementResults":null,"RelevantResults":

Thank you in advance!
