### ISSUE TITLE
Getting GetListItemChangesSinceToken via phpSPO

### ISSUE THREAD

**Issue by MartijnDevNull** [vgrem/phpSPO#14]
Hello,

This is a feature request,

I'm [trying to get the latest changes](https://stackoverflow.com/questions/36626004/sharepoint-getlistitemchangessincetoken-curl-request-in-php) in my Sharepoint using your SDK and I was wondering if this could be implemented in the SDK?

Thanks, your SDK makes my life **much** easier

**Comment by vgrem** [comment]
Greetings!

[SharePoint REST Client SDK for PHP][1] now supports [`GetListItemChangesSinceToken`][2] and `GetChanges` methods (for `Web` & `List` resources)


**First approach**

The following example demonstrates how to utilize [`GetListItemChangesSinceToken method`][2]:

    $listTitle = "Documents";
    $payload = array(
        'query' => array(
            '__metadata' => array('type' => 'SP.ChangeLogItemQuery'),
            'ViewName' => '',
            'QueryOptions'=> '<QueryOptions><Folder>Shared Documents</Folder></QueryOptions>'
        )
    );

    $request = new ClientRequest($webUrl,$authCtx);
    $options = array(
        'url' => $webUrl . "/_api/web/Lists/GetByTitle('$listTitle')/GetListItemChangesSinceToken",
        'data' => json_encode($payload),
        'method' => 'POST'
    );
    $response = $request->executeQueryDirect($options);

    //process results
    $xml = simplexml_load_string($response);
    $xml->registerXPathNamespace('z', '#RowsetSchema');
    $rows = $xml->xpath("//z:row");
    foreach($rows as $row) {
        print (string)$row->attributes()["ows_FileLeafRef"] . "\n";
    }




**Second approach**

Since [SharePoint REST Client SDK for PHP][1] now supports [`GetListItemChangesSinceToken method`][2], the previous example could be invoked like this:   

    $list = $ctx->getWeb()->getLists()->getByTitle($listTitle);
    $query = new ChangeLogItemQuery();
    //to request all the items set ChangeToken property to null  
    $query->ChangeToken = "1;3;e49a3225-13f6-47d4-a146-30d9caa05362;635969955256400000;10637059";
    $items = $list->getListItemChangesSinceToken($query);
    $ctx->executeQuery();
    foreach ($items->getData() as $item) {
        print "[List Item] $item->Title\r\n";
    }


More examples could be found [here][3] under [phpSPO][1] repository.


  [1]: https://github.com/vgrem/phpSPO
  [2]: https://msdn.microsoft.com/en-us/library/office/websvclists.lists.getlistitemchangessincetoken.aspx
  [3]: https://github.com/vgrem/phpSPO/blob/master/examples/change_examples.php
