### ISSUE TITLE
Number of rows in getItems

### ISSUE THREAD

**Issue by tonisanta** [vgrem/phpSPO#159]
Hi,I was trying to get all the items from a list 
`$remoteList = $web->getLists()->getByTitle(xxx)` 
`$listData = $remoteList->getItems();`
however in the $remoteList properties in the array of Data there are only 100 rows, and the list has more than 100 items. I saw that it's a common problem, however I don't know which solution I should consider for this library. 
https://sharepoint.stackexchange.com/questions/74777/list-api-get-all-items-limited-to-100-rows

**Comment by vgrem** [comment]
Greetings!

[`v2.4.1` release](https://github.com/vgrem/phpSPO/releases/tag/v2.4.1) specifically addresses this issue, i.e. working with large lists and libraries and i suggest to upgrade to this version. 


## Working with SharePoint large lists and libraries (which contains more than `5000` items)

Due to built-in support, nothing has changed in terms how list items are retrieved to preserve API simplicity, no matter how many items list contains (unless $top query option is provided to restrict the amount of items to load)
_Behind the scene, lazy loading approach is utilized to retrieve paged data, which offers optimal performance since the data is getting load only when requested_

$list = $ctx->getWeb()->getLists()->getByTitle("--Large List Title--");
$items = $list->getItems();
$ctx->load($items);
$ctx->executeQuery();

print $items->getCount() . PHP_EOL;  //prints the actual amount of items in list/library

//enumerate across All list items 
foreach ($items as $index => $item){
    print($index . ":" . $item->getProperty('Title') . PHP_EOL);
}
