### ISSUE TITLE
How to upload large files (> 250 MB)?

### ISSUE THREAD

**Issue by ugalviar** [vgrem/phpSPO#176]
I am able to upload files using your example but getting the following exception for large files:

The request message is too big. The server does not allow messages larger than 262144000 bytes.

Any help much appreciated.

**Comment by vgrem** [comment]
Greetings,

[this is expected behavior](https://docs.microsoft.com/en-us/archive/blogs/sharepointdevelopersupport/always-use-file-chunking-to-upload-files-250-mb-to-sharepoint-online), in SharePoint Online, you will be limited to the 250 MB file limit.
To upload a large file (more then 250 MB),  `FileCollection.createUploadSession` method could be utilized which upload a file as fragments (chunks) via upload session API



Complete example

```
$ctx = ClientContext::connectWithClientCredentials($Url, $ClientId, $ClientSecret);
    $localPath = "../data/big_buck_bunny.mp4";
    $targetLibraryTitle = "Documents";
    $targetList = $ctx->getWeb()->getLists()->getByTitle($targetLibraryTitle);

    $session = $targetList->getRootFolder()->getFiles()->createUploadSession($localPath, "big_buck_bunny.mp4",
    function ($uploadedBytes) {
        echo "Progress: $uploadedBytes bytes uploaded .." . PHP_EOL;
    });

    $ctx->executeQuery();
    $targetFileName = $session->getFile()->getName();
    echo "File $targetFileName has been uploaded.";
```
