### ISSUE TITLE
How to reference the Shared Documents library

### ISSUE THREAD

**Issue by hnpilot** [vgrem/phpSPO#195]
I am trying to upload file(s) to Shared Documents folder in Sharepoint Online.

I can get the authentication to go all right but don't seem to able to figure out how to address the Shared Documents-file library.

$ctx = ClientContext::connectWithUserCredentials("https://organizationcom.sharepoint.com/sites/uploadedfiles","Login.Name@organisation.org","HighlySafeP@ssw0rd");
$targetLibraryTitle = rawurlencode("Shared Documents/");
$targetList = $ctx->getWeb()->getLists()->getByTitle($targetLibraryTitle);

but it dies with this one

List 'Shared%20Documents%2F' does not exist at site with URL 'https://organizationcom.sharepoint.com/sites/uploadedfiles'

But if I look at the browser address line it says 'https://organizationcom.sharepoint.com/sites/uploadedfiles/Shared%20Documents/Forms/AllItems/....

Am I doing something totally wrong, or is there something that is not working. I have tried all kind of permutations with slashes, %20 etc but it is of course also possible that I have missed just the right form.

I used to to do sharepoint-programming with on premises SP, but now been in the heaven of Linux programming (until O365 and this came...)

wbr 
hank

**Comment by vgrem** [comment]
Greetings!

based on your detailed and through explanation, most likely this is indeed an addressing issue. 

`Lists.getByTitle` method expects the _list title_ . 

Given the provided url:  `https://organizationcom.sharepoint.com/sites/uploadedfiles/Shared%20Documents/Forms/AllItems/....` 
 most likely the title of this library is `Documents` , so if you change it to:

```
$list =  $client->getWeb()->getList("Documents");
$client->load($list);
$client->executeQuery();

```
most likely it will succeed.


Now you might wounder could the library be addressed  by `url` (e.g. `/sites/uploadedfiles/Shared Documents`) instead of `title` (e.g. `Documents`), the answer is also positive, here is an example:   

```
$listFolder = $ctx->getWeb()->getFolderByServerRelativeUrl("/sites/uploadedfiles/Shared Documents")->expand("Properties");
$ctx->load($listFolder);
$ctx->executeQuery();


$listId = $listFolder->getProperty("Properties")["vti_x005f_listname"];    //<-system prop contains List Id
$list = $ctx->getWeb()->getLists()->getById($listId);



```

Starting from the next version, `List` could be addressed in a more concise manner (since `Web.List` method will be exposed) by Url like this:

```
$list =  $client->getWeb()->getList("/sites/uploadedfiles/Shared Documents");
$client->load($list);
$client->executeQuery();

```





Regarding:

> I used to to do sharepoint-programming with on premises SP, but now been in the heaven of Linux programming (until O365 and this came...)

i feel you, being myself a long time Linux proponent, and this project is no exception, all the development is held on Ubuntu machine.

Vadim

**Comment by hnpilot** [comment]
Thank you, Vadim

I'll check this tomorrow (already worked for more than 10 hours today), but I think I now understand the reason why I had the problems. 

Most probably your solution will work fine. I'll report here tomorrow whatever happens :)

hank

**Comment by hnpilot** [comment]
Just to report, that at least the procedure you gave using the relative path gives the wanted result :) 

I prefer it, feels like a bit more robust than relying on the list name.

hank
