### ISSUE TITLE
Cannot upload small files to SharePoint with createUploadSession

### ISSUE THREAD

**Issue by ax1mx2** [vgrem/phpSPO#201]
Smaller files around 100-200KB are not uploaded to SharePoint.

The resulting in files in SharePoint have the correct names but are of size 0B, when one tries to download them.

```php
echo filesize($localFilename); // Returns something like 194523

$ctx->getWeb()
    ->getLists()
    ->getByTitle($pathParts[0])
    ->getRootFolder()
    ->getFiles()
    ->createUploadSession($localFilename, $targetFilename, function ($bytes) {
        echo $bytes; // Returns the correct filesize, but apparently no bytes are uploaded.
    });
$ctx->executeQuery();
```

**Comment by DocCobra** [comment]
It's because when passing through a file smaller than the chunkSize, it doesn't commit and finalize the upload. 
I put a bandaid on it by editing buildQuery, in UploadSession.php. 

`
while (!feof($handle)) {  
  $buffer = fread($handle, $chunkSize);
  $bytesRead = ftell ( $handle );
  if ($firstChunk) {
    $uploadFile->startUpload($this->uploadSessionId, $buffer);
    $firstChunk = false;
  } 
  else {
    $uploadFile->continueUpload($this->uploadSessionId, $offset, $buffer);
  }
  if ($fileSize == $bytesRead) {
    $this->targetFile = $uploadFile->finishUpload($this->uploadSessionId, $offset, $buffer);
  }
  $offset = $bytesRead;
  unset($buffer); 
}
fclose($handle);
`

**Comment by vgrem** [comment]
Greetings,

would recommend the following approach in this regard:

- given 4-MB file upload limit, if file size exceeds this limit, utilize [Chunk upload session](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/dn781478(v=office.15)?redirectedfrom=MSDN) endpoints
- otherwise upload a file via [default upload endpoint](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj838377(v=office.15)) 


Here is an example:

```php

$client = (new ClientContext($webUrl))->withCredentials($credentials);

$sourceFileName = "./SharePoint User Guide.docx";
$targetLibraryTitle = "Documents";
$targetList = $client->getWeb()->getLists()->getByTitle($targetLibraryTitle);


$maxUploadSize = 1024 * 1024 * 4; //4MB
if(filesize($sourceFileName) < $maxUploadSize){
    $uploadFile = $targetList->getRootFolder()->uploadFile(basename($sourceFileName),file_get_contents($sourceFileName));
    $client->executeQuery();
    printf($uploadFile->getServerRelativeUrl());
}
else{
    $session = $targetList->getRootFolder()->getFiles()->createUploadSession($sourceFileName, basename($sourceFileName),
        function ($uploadedBytes) {
            echo "Progress: $uploadedBytes bytes uploaded .." . PHP_EOL;
        });
    $client->executeQuery(); //3. submit a query
    printf($session->getFile()->getServerRelativeUrl());
}

```
