### ISSUE TITLE
Documents thumbnails

### ISSUE THREAD

**Issue by marti85cr** [vgrem/phpSPO#220]
How do I get the thumbnail of a document?

I tried https://natechamberlain.com/2020/05/14/add-a-thumbnail-column-for-documents-and-media-in-a-sharepoint-online-document-library/

and 

https://www.c-sharpcorner.com/article/thumbnail-or-preview-of-files-in-sharepoint-document-library-using-column-format/

and I can see the generated thumbnails in the Document List, but I can't retrieve them within my phpspo app

My code goes roughly like this
...
	$files = $ctx->getWeb()->getFolderByServerRelativeUrl($relativeURL)->getFiles()->expand("ListItemAllFields");
	$ctx->load($files);
...
	foreach ($files->getData() as $file) {
		$properties = $file->getListItemAllFields();
...
		$thumbnail= $properties->Thumbnail;
		$preview = $properties->Preview;
...

but both results are empty		

any ideas?

**Comment by vgrem** [comment]
Greetings!

In your example the request is actually never getting submitted to the server, this is what `ClientContext->executeQuery()` method  intended  for.


Here is an updated version:


```
$files = $ctx->getWeb()->getFolderByServerRelativeUrl("Pictures")->getFiles()->expand("ListItemAllFields");
$ctx->load($files);
$ctx->executeQuery();

```

or via Fluent syntax:

`$files = $ctx->getWeb()->getFolderByServerRelativeUrl("Pictures")->getFiles()->expand("ListItemAllFields")-get()->executeQuery()
`

**Comment by marti85cr** [comment]
Thanks for your response, I do have the "$ctx->executeQuery();" line in my code (I put "..." for such code), and I can access other columns (such as Title, Created, ServerRedirectedEmbedUrl, etc). but when I request for Thumbnail or Preview columns (which in sharepoint I can see) 

I was also wondering if there's an example for a request to the API like this 

https://tenant.sharepoint.com/sites/ExampleSite/_api/SP.Publishing.EmbedService/EmbedData?url='http://www.example.com/picture.jpg'&version=1

I've found an EmbedService.php but I can't tell how it's supposed to be used,

Best regards...

**Comment by vgrem** [comment]
All right, since it is getting more clear (although  revealing information about  source list where images stored might also be beneficial) the following approach could be considered instead for  retrieval Thumbnail or Preview field values.

Assuming images are stored in out-of-the-box Pictures List (or with a similar schema), images metadata:

- `EncodedAbsUrl `-
- `EncodedAbsThumbnailUrl`: image thumbnail, returned in the following format: `https://{tenant}.sharepoint.com/Pictures/_t/{filename}`
- `EncodedAbsWebImgUrl`  

```php
$picturesList = $ctx->getWeb()->getLists()->getByTitle("Pictures");
$items = $picturesList->getItems()->select("EncodedAbsThumbnailUrl,EncodedAbsWebImgUrl")->get()->executeQuery();

/** @var ListItem $item */
foreach ($items as $item) {
    print($item->getProperty("EncodedAbsThumbnailUrl"));
} 
```


Regarding another options, indeed  alternative `SP.Publishing.EmbedService/EmbedData` or `/_layouts/15/getpreview.ashx`  endpoints might be the utilized instead. They are not supported  by library (yet)  but  could be invoked via custom requests. [The following example](https://github.com/vgrem/phpSPO/issues/202#issuecomment-701493268) demonstrates how to construct a custom request.
