### ISSUE TITLE
Not working for german language sharepoint.

### ISSUE THREAD

**Issue by AakashDesaiAD** [vgrem/phpSPO#279]
When i download all documents from the "Documents" list with Default Sharepoint language English, its works fine. but not working fine with German language, its throw an error that I given below,

{"error":{"code":"-1, System.ArgumentException","message":{"lang":"de-DE","value":"Die Liste '/sites/{mysitename}/Shared Documents' ist in der Website mit der URL 'https://{mycompanyname}.sharepoint.com/sites/{mysitename}' nicht vorhanden."}}}

code

`$sourceLibraryTitle = "Documents";

$sourceList = $client->getWeb()->getLists()->getByTitle($sourceLibraryTitle);

$files = $sourceList->getRootFolder()->getFiles();

$client->load($files);

$client->executeQuery();`

**Comment by vgrem** [comment]
Greetings,

most likely the error occurs since no list exist with corresponding title on provided site:

```
getByTitle($sourceLibraryTitle)
            ^^^^^^^^^^^^^^^^^
        expects list or library title 
```

`getByTitle` method expects list `Title` property (which usually differ from list `Url`), meaning `$sourceLibraryTitle` should correspond to library title. 





If you prefer to retrieve list by its url, `getList` method from `Web` class could be utilized, for instance: 


`$list = $client->getWeb()->getList("/sites/{mysitename}/Shared Documents")->executeQuery();`
