### ISSUE TITLE
Can't get subfolders/subfiles for folder with special chars like # (SharePoint)

### ISSUE THREAD

**Issue by Anatoliy-Gerasimov** [vgrem/phpSPO#96]

**Comment by vgrem** [comment]
Greetings,
indeed, the following example fails when the file name contains special character (`#` in this case)

```
$fileUrl = "/Shared Documents/Guide #123.docx";
$file = $ctx->getWeb()->getFileByServerRelativeUrl($fileUrl);
$ctx->load($file);
$ctx->executeQuery();
```
in particular it throws the exception:

> The file `/Shared Documents/Guide #123.docx` does not exist. 


The following examples demonstrate how to retrieve folder/file when its name contain special characters:

It seems [`SP.Web.getFileByServerRelativeUrl` method](https://msdn.microsoft.com/en-us/library/office/jj246729.aspx) itself is the root cause of this behavior and a bug needs to be reported to Microsoft.  

Another options, for example  [FileCollection.GetByUrl](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.filecollection.getbyurl.aspx) method support if name contains special characters. 

 

**Example**

Loading folder properties via [`Web.getFolderByServerRelativeUrl` method](https://github.com/vgrem/phpSPO/blob/cbf0ba855f394aae08ffc8d382630c936e5ee008/src/SharePoint/Web.php#L201):

```
$folderUrl = "/Shared Documents/Samples #";
$folder = $ctx->getWeb()->getFolderByServerRelativeUrl($folderUrl);
$ctx->load($folder);
$ctx->executeQuery();
```


Loading file properties via [`FileCollection.getByUrl` method](https://github.com/vgrem/phpSPO/blob/3318c782b8e1c1c1f274fb0bb37efab3a5274bee/src/SharePoint/FileCollection.php#L62):

  ```
  $folderUrl = "Shared Documents";
  $fileUrl = "Guide #123.docx";
  file = $ctx->getWeb()->getFolders()->getByUrl($folderUrl)->getFiles()->getByUrl($fileUrl);
  $ctx->load($file);
  $ctx->executeQuery();
  print "File name: '{$file->getProperty("Name")}'\r\n";
```

**Comment by Anatoliy-Gerasimov** [comment]
Thank you very much for your help
